# Generated by Django 2.2.5 on 2020-02-06 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='r_img',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
